/**
* Retrieves a random sentence and returns that sentence. (I know how bad this is or can be. This is only for demo)
* @return {String} Pseudo-random string
*/

const randomSentence = () => {
  // Sentences generated by ChatGPT-3.5, sorry but I am not a creative writer.
  const sentences = [
    "In the heart of the enchanted forest, mystical creatures gather at the moonlit clearing, sharing ancient tales that echo through the rustling leaves and twinkling fireflies. As night deepens, the forest becomes a magical tapestry woven with the threads of imagination and wonder.",
    "Amidst the cosmic dance of celestial bodies, a lone comet streaks across the night sky, leaving a trail of stardust as it ventures through the vastness of the universe. Planets and constellations bear witness to the celestial spectacle, casting a mesmerizing glow that captivates astronomers and dreamers alike.",
    "Within the virtual realm of Cyberspace, digital avatars embark on epic quests, exploring pixelated landscapes and battling formidable foes in a quest for virtual supremacy. In this digital arena, friendships are forged, and legends are born within the circuits and code of the digital frontier.",
    "On the shores of Atlantis, archaeologists unveil the remnants of an ancient civilization, piecing together the mysteries of a lost world beneath the depths of the ocean. Sunken temples and intricate carvings tell stories of a prosperous society that vanished beneath the waves.",
    "In the bustling city of Neonopolis, sentient robots and humans coexist, navigating the neon-lit streets where futuristic technology meets timeless traditions. Amidst the vibrant energy, a fusion of cultures and technologies creates a metropolis that pulses with life, where the future unfolds in a dazzling display of innovation and diversity."
  ];

  return sentences[Math.floor(Math.random() * (sentences.length - 1))];
}

module.exports = randomSentence;